version: '3.8'
services:
  app:
    build: .
    container_name: mylists-app
    ports:
      - "3000:3000"
    volumes:
      - ./instance:/usr/src/app/instance
      - ./static:/usr/src/app/static
    environment:
      - DATABASE_URL=file:./instance/site.db
      - REDIS_ENABLED=true
      - REDIS_URL=redis://redis:6379
      # 其他必要的环境变量可以在这里添加或通过 .env 文件加载
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: mylists-redis
    restart: always
